# Generated by Django 5.0.2 on 2024-02-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='reference_id',
            new_name='reader_ref_id',
        ),
    ]
