# Generated by Django 5.0.2 on 2024-02-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_remove_reader_reader_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='reader_ref_id',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_contact',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_name',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
