# Generated by Django 5.0.2 on 2024-02-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0004_reader_reader_ref_id_alter_reader_reader_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='reader_ref_id',
            new_name='reference_id',
        ),
    ]
