# Generated by Django 5.0.2 on 2024-03-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0005_rename_reader_ref_id_reader_reference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=255)),
                ('book_author_name', models.CharField(max_length=100)),
                ('book_description', models.TextField()),
            ],
        ),
    ]
