# Generated by Django 5.0.2 on 2024-03-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0006_booksdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksdata',
            name='cntOfBooks',
            field=models.IntegerField(default=0),
        ),
    ]
