# Generated by Django 5.0.2 on 2024-03-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0007_booksdata_cntofbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='myCartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id_in_cart', models.IntegerField(default=0)),
                ('book_name_in_cart', models.CharField(max_length=100)),
                ('totalCount', models.IntegerField(default=0)),
            ],
        ),
    ]
