# Generated by Django 5.0.2 on 2024-03-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0008_mycartdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.IntegerField(default=0)),
                ('bookName', models.CharField(max_length=250)),
                ('readerId', models.IntegerField(default=0)),
                ('readerName', models.CharField(max_length=255)),
                ('readerContact', models.IntegerField(default=0)),
            ],
        ),
    ]
