# Generated by Django 5.0.2 on 2024-03-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0010_rentalbookdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='rentedBooksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.IntegerField()),
                ('reader_name', models.CharField(max_length=255)),
                ('book_name', models.CharField(max_length=255)),
                ('readerContact', models.CharField(max_length=12)),
                ('rented_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='returnbooks',
            name='readerContact',
        ),
    ]
